# Generated by Django 3.1.1 on 2020-10-03 08:37

from django.db import migrations, models
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secret_answer',
            field=encrypted_fields.fields.EncryptedCharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='secret_question',
            field=encrypted_fields.fields.EncryptedTextField(choices=[('PET', "What's your pet name?"), ('PN', "What's your phone number"), ('BF', "What's your best friend name")], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
